spring:
  redis:
    host: localhost
    port: 6379
  r2dbc:
    url: r2dbc:mysql://localhost:3306/realworld?serverTimezone=UTC
    username: realadmin
    password: realadmin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
      jdbc:
        lob:
          non_contextual_creation: true

# 추가 설정 - R2DBC에서 Database로 나가는 쿼리를 보고 싶으면 아래처럼 로깅레벨을 설정해야 함
logging:
  level:
    org.springframework.r2dbc.core: debug